# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3fb250d48223e79fe9eaaf9f4858919"
name = "image-uplode"
application_url = "https://prozac-fields-definitions-peer.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "nonedit.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://prozac-fields-definitions-peer.trycloudflare.com/auth/callback",
  "https://prozac-fields-definitions-peer.trycloudflare.com/auth/shopify/callback",
  "https://prozac-fields-definitions-peer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
